version: '2'
services:
    webserver:
        image: airflow:latest
        container_name: airflow-web
        volumes:
             - /your/path/dags:/home/airflow/dags
             - /your/path/logs:/home/airflow/logs
        ports:
            - "8080:8080"
        entrypoint: /home/airflow/webserver_entrypoint.sh
        user: airflow


    scheduler:
        image: airflow:latest
        container_name: airflow-scheduler
        depends_on:
            - webserver
        volumes:
             - /your/path/dags:/home/airflow/dags
             - /your/path/logs:/home/airflow/logs
        entrypoint: /home/airflow/scheduler_entrypoint.sh
        user: airflow
