version: '2'
services:
    webserver:
        image: airflow:latest
        container_name: airflow-web
        env_file:
            - env_vars_web
        volumes:
             - /your/path/dags:/home/airflow/dags
             - /your/path/logs:/home/airflow/logs
        ports:
            - "8080:8080"
        user: airflow


    scheduler:
        image: airflow:latest
        container_name: airflow-scheduler
        env_file:
            - env_vars_scheduler
        depends_on:
            - webserver
        volumes:
             - /your/path/dags:/home/airflow/dags
             - /your/path/logs:/home/airflow/logs
        user: airflow
